# Project Details
p_name = Example Mod
p_id = BetterKeybindMenu
p_group = com.examplemod.exmod
p_desc = This is the example mod\
  for Cosmic\
  Reach
p_author = Crab and Lemon
p_version = 1.0.0-alpha

# Cosmic Reach
cosmic_reach_version = 0.5.26-alpha

# Puzzle Loader
puzzle_loader_cosmic_version = 1.7.3-alpha
puzzle_loader_core_version = 1.4.1-alpha

# Puzzle Gradle
puzzle_jigsaw_suite = 1.4.0-beta

# Gradle
org.gradle.jvmargs=-Xmx4096M
